### ISSUE TITLE
simulation fails immediately when when docker service unavailable

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/rodrigues#14]
Simulation goes to "FAILURE" state immediately, but there is nothing in the status screen to explain this. Worker output is:

 ```
$ fig logs worker
Attaching to ceilingkat_worker_1
worker_1 | [2014-11-27 12:56:52,140: ERROR/MainProcess] Task
simqueue.tasks.simulate[4f06c430-dbc1-44fc-897e-00e11ad87095] raised
unexpected: APIError("HTTPError('404 Client Error: Not Found',)",)
worker_1 | Traceback (most recent call last):
worker_1 |   File
"/usr/local/lib/python3.4/dist-packages/celery/app/trace.py", line
240, in trace_task
worker_1 |     R = retval = fun(*args, **kwargs)
worker_1 |   File
"/usr/local/lib/python3.4/dist-packages/celery/app/trace.py", line
438, in __protected_call__
worker_1 |     return self.run(*args, **kwargs)
worker_1 |   File "/code/simqueue/tasks.py", line 36, in simulate
worker_1 |     simulation=simulation)
worker_1 |   File "/code/simqueue/dockering.py", line 83, in run_docker
worker_1 |     for row in client.build(path=dockerfile_dir, tag=image_name):
worker_1 |   File
"/usr/local/lib/python3.4/dist-packages/docker/client.py", line 281,
in _stream_helper
worker_1 |     socket_fp = self._get_raw_response_socket(response)
worker_1 |   File
"/usr/local/lib/python3.4/dist-packages/docker/client.py", line 261,
in _get_raw_response_socket
worker_1 |     self._raise_for_status(response)
worker_1 |   File
"/usr/local/lib/python3.4/dist-packages/docker/client.py", line 89, in
_raise_for_status
worker_1 |     raise errors.APIError(e, response, explanation=explanation)
worker_1 | docker.errors.APIError: HTTPError('404 Client Error: Not Found',)
worker_1 | [2014-11-27 12:56:56,625: INFO/MainProcess] Received task:
simqueue.tasks.simulate[1392e8a0-3002-421b-bce6-aa6561c0b2e2]
worker_1 | [2014-11-27 12:56:56,644: INFO/Worker-3] starting simulation 1
worker_1 | [2014-11-27 12:56:56,711: ERROR/MainProcess] Task
simqueue.tasks.simulate[1392e8a0-3002-421b-bce6-aa6561c0b2e2] raised
unexpected: APIError("HTTPError('404 Client Error: Not Found',)",)
worker_1 | Traceback (most recent call last):
worker_1 |   File
"/usr/local/lib/python3.4/dist-packages/celery/app/trace.py", line
240, in trace_task
worker_1 |     R = retval = fun(*args, **kwargs)
worker_1 |   File
"/usr/local/lib/python3.4/dist-packages/celery/app/trace.py", line
438, in __protected_call__
worker_1 |     return self.run(*args, **kwargs)
worker_1 |   File "/code/simqueue/tasks.py", line 36, in simulate
worker_1 |     simulation=simulation)
worker_1 |   File "/code/simqueue/dockering.py", line 83, in run_docker
worker_1 |     for row in client.build(path=dockerfile_dir, tag=image_name):
worker_1 |   File
"/usr/local/lib/python3.4/dist-packages/docker/client.py", line 281,
in _stream_helper
worker_1 |     socket_fp = self._get_raw_response_socket(response)
worker_1 |   File
"/usr/local/lib/python3.4/dist-packages/docker/client.py", line 261,
in _get_raw_response_socket
worker_1 |     self._raise_for_status(response)
worker_1 |   File
"/usr/local/lib/python3.4/dist-packages/docker/client.py", line 89, in
_raise_for_status
worker_1 |     raise errors.APIError(e, response, explanation=explanation)
worker_1 | docker.errors.APIError: HTTPError('404 Client Error: Not Found',)
```

**Comment by gijzelaerr** [comment]
this has been fixed
