### ISSUE TITLE
problem with parsing form

### ISSUE THREAD

**Issue by gijzelaerr** [ska-sa/rodrigues#34]
```
2015/03/26 09:39:44 INFO: ## Thu Mar 26 09:39:44 2015:
/usr/bin/pyxis CFG=/storage/18-41b75cm2/input/parameters.json OUTFILE=//storage/18-41b75cm2/output/results OUTDIR=/storage/18-41b75cm2/output azishe
2015/03/26 09:39:44 PYXIS: running command azishe
Traceback (most recent call last):
File "/usr/bin/pyxis", line 281, in <module>
Pyxis.Internals.run(*commands);
File "/usr/lib/python2.7/dist-packages/Pyxis/Internals.py", line 1098, in run
comcall();
File "./pyxis-ckat.py", line 30, in azishe
ms_opts, im_opts, _deconv = load_from_json(cfg)
File "./pyxis-base.py", line 187, in load_from_json
POSITIONS = '%s/%s'%(OBSDIR,_OBS[OBSERVATORY])
KeyError: u'kat'
2015/03/26 09:39:44 ERROR: Exception raised, aborting
2015/03/26 09:41:15 INFO: ## Thu Mar 26 09:41:14 2015:
/usr/bin/pyxis CFG=/storage/18-41b75cm2/input/parameters.json OUTFILE=//storage/18-41b75cm2/output/results OUTDIR=/storage/18-41b75cm2/output azishe
2015/03/26 09:41:15 PYXIS: running command azishe
Traceback (most recent call last):
File "/usr/bin/pyxis", line 281, in <module>
Pyxis.Internals.run(*commands);
File "/usr/lib/python2.7/dist-packages/Pyxis/Internals.py", line 1098, in run
comcall();
File "./pyxis-ckat.py", line 30, in azishe
ms_opts, im_opts, _deconv = load_from_json(cfg)
File "./pyxis-base.py", line 187, in load_from_json
POSITIONS = '%s/%s'%(OBSDIR,_OBS[OBSERVATORY])
KeyError: u'kat'
2015/03/26 09:41:15 ERROR: Exception raised, aborting
```

**Comment by SpheMakh** [comment]
Could we have the simulation ID for these errors, so I can have proper look at what's going on. Or include the parameter file.

**Comment by gijzelaerr** [comment]
http://192.168.0.149/viewer/24/overview/
