### ISSUE TITLE
another problem with parsing form

### ISSUE THREAD

**Issue by gijzelaerr** [ska-sa/rodrigues#35]
http://192.168.0.149/viewer/8/overview/

```
2015/03/26 09:40:54 PYXIS: meqtree-pipeliner.py succeeded
2015/03/26 09:40:54 INFO: MODEL_DATA + CORRECTED_DATA --> CORRECTED_DATA : rows 0-36288
2015/03/26 09:40:54 INFO: MODEL_DATA + CORRECTED_DATA --> CORRECTED_DATA : rows 36288-72576
2015/03/26 09:40:54 INFO: MODEL_DATA + CORRECTED_DATA --> CORRECTED_DATA : rows 72576-108864
2015/03/26 09:40:54 INFO: MODEL_DATA + CORRECTED_DATA --> CORRECTED_DATA : rows 108864-145152
2015/03/26 09:40:54 INFO: MODEL_DATA + CORRECTED_DATA --> CORRECTED_DATA : rows 145152-181440
2015/03/26 09:40:54 INFO: im.lwimager.make_image: making dirty image //storage/8-gbwzduss/output/results-dirty.fits
Traceback (most recent call last):
File "/usr/bin/pyxis", line 281, in <module>
Pyxis.Internals.run(*commands);
File "/usr/lib/python2.7/dist-packages/Pyxis/Internals.py", line 1098, in run
comcall();
File "./pyxis-ckat.py", line 153, in azishe
try: restore[key] = float(val)
TypeError: float() argument must be a string or a number
```

**Comment by SpheMakh** [comment]
fixed in a1cb6b11356fb97c5a1e76706d42ca2193035100
