### ISSUE TITLE
another problem parsing form ;)

### ISSUE THREAD

**Issue by gijzelaerr** [ska-sa/rodrigues#36]
http://192.168.0.149/viewer/20/overview/
```
2015/03/26 09:44:33 INFO: im.lwimager.make_image: making dirty image //storage/20-ahootssa/output/results-dirty.fits
Traceback (most recent call last):
File "/usr/bin/pyxis", line 281, in <module>
Pyxis.Internals.run(*commands);
File "/usr/lib/python2.7/dist-packages/Pyxis/Internals.py", line 1098, in run
comcall();
File "./pyxis-ckat.py", line 130, in azishe
noise = madnoise(dirty_image,channelise=CHANNELIZE,freq_axis=0)
File "./pyxis-base.py", line 331, in madnoise
data = imdata(fitsname,channelise=channelise,freq_axis=freq_axis)
File "./pyxis-base.py", line 492, in imdata
return data[img]
IndexError: index 4 is out of bounds for axis 0 with size 4
```

**Comment by SpheMakh** [comment]
fixed in a1cb6b11356fb97c5a1e76706d42ca2193035100
