### ISSUE TITLE
Failing jobs don't give feedback to user in terminal output.

### ISSUE THREAD

**Issue by JulienNGirard** [ska-sa/rodrigues#60]
Problem:
The job terminal output will always show "running..." and never finished.

The similar issue might be experienced by the "Anna demo" and "Tokolo" jobs, created respectively on June 9 and June 2.

Test done on rodrigues.meqtrees.net:
- Using a custom image: (I guess it is not the problem)
[M31_256.fits.zip](https://github.com/ska-sa/rodrigues/files/341364/M31_256.fits.zip)

and default parameters including:
- Use default imaging settings checked
- LWIMAGER deconvolution settings checked
- CASA deconvolution settings checked

This bug was reproduced in parallel on a local RODRIGUES build using the same image and the same parameters.

tail of the output of docker-compose logs worker.

```
worker_1  | 
worker_1  | [2016-06-30 14:02:16,299: INFO/MainProcess] Connected to amqp://guest:**@broker:5672//
worker_1  | [2016-06-30 14:02:16,308: INFO/MainProcess] mingle: searching for neighbors
worker_1  | [2016-06-30 14:02:17,318: INFO/MainProcess] mingle: all alone
worker_1  | [2016-06-30 14:02:17,358: WARNING/MainProcess] celery@5de99c98941b ready.
worker_1  | [2016-06-30 14:06:09,551: INFO/MainProcess] Received task: scheduler.tasks.run_job[2c2d90d5-f5e2-4fdf-adfd-8f226ef9d404]
worker_1  | [2016-06-30 14:06:09,586: INFO/Worker-1] starting job 1
worker_1  | [2016-06-30 14:06:09,887: ERROR/MainProcess] Task scheduler.tasks.run_job[2c2d90d5-f5e2-4fdf-adfd-8f226ef9d404] raised unexpected: TypeError("'bool' object is not subscriptable",)
worker_1  | Traceback (most recent call last):
worker_1  |   File "/usr/local/lib/python3.4/dist-packages/celery/app/trace.py", line 240, in trace_task
worker_1  |     R = retval = fun(*args, **kwargs)
worker_1  |   File "/usr/local/lib/python3.4/dist-packages/celery/app/trace.py", line 438, in __protected_call__
worker_1  |     return self.run(*args, **kwargs)
worker_1  |   File "/code/scheduler/tasks.py", line 66, in run_job
worker_1  |     host_storage = path.join(path.realpath(settings.HOST_STORAGE), job.results_dir)
worker_1  |   File "/usr/lib/python3.4/posixpath.py", line 372, in realpath
worker_1  |     path, ok = _joinrealpath(filename[:0], filename, {})
worker_1  | TypeError: 'bool' object is not subscriptable

```

**Comment by gijzelaerr** [comment]
This should be solved now, it was a configuration issue with the HOST_STORAGE setting which should be correctly set now.
